Repository Quick-Command/QuickCommand, pull requests merged in 2021-05, with the labels that each got.

#11 Add mock data
  package-lock.json
  src/app/store.js
  src/components/DatabaseMenu/DatabaseMenu.js
  src/features/counter/counterAPI.js
  src/features/counter/counterSlice.js
Labels: good first issue

#23 Feature/icons
  cypress/integration/quick-command-tests.js
  public/qc-logo-6.jpeg
  public/qc-logo-7-removebg-preview.png
  public/qc-logo-8.png
  src/API-calls.js
  src/Icons/earthquake.svg
  src/Icons/fire.svg
  src/Icons/flood.svg
  src/Icons/hurricane.svg
  src/Icons/shooting.svg
  src/Icons/tornado.svg
  src/Store/Store.js
  src/Store/store.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/ChartView/ChartView.css
  src/components/ChartView/ChartView.js
  src/components/ChartView/ChartViewSlice.js
  src/components/Footer/Footer.css
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/IncidentForm/IncidentForm.js
  src/components/IncidentInfo/IncidentInfo.css
  src/components/IncidentInfo/IncidentInfo.js
  src/components/OngoingIncidents/OngoingIncidents.css
  src/components/OngoingIncidents/OngoingIncidents.js
  src/components/OrgChart/OrgChart.js
  src/components/Profiles/Profiles.css
  src/components/Profiles/Profiles.js
  src/components/ResolvedIncidents/ResolvedIncidents.css
  src/components/ResolvedIncidents/ResolvedIncidents.js
  src/components/app/App.css
  src/components/app/App.js
  src/logo.svg
Labels: feature, frontend

#25 Incident containers
  src/Icons/earthquake.svg
  src/Icons/gripfire-brands.svg
  src/components/App/App.css
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/IncidentForm/IncidentForm.css
  src/components/IncidentsMenu/IncidentsMenu.css
  src/components/OngoingIncidents/OngoingIncidents.css
  src/components/OngoingIncidents/OngoingIncidents.js
  src/components/ResolvedIncidents/ResolvedIncidents.css
  src/components/ResolvedIncidents/ResolvedIncidents.js
  src/utilities.js
Labels: enhancement, frontend

#26 Chage stylings for links and move icon function to utilities
  cypress/videos/quick-command-tests.js.mp4
  src/Icons/accident.svg
  src/Icons/earthquake.svg
  src/Icons/earthquakeMod.svg
  src/Icons/fire.svg
  src/Icons/flood.svg
  src/Icons/hazard.svg
  src/Icons/hazmat.svg
  src/Icons/power.svg
  src/Icons/shooting.svg
  src/Icons/tornado.svg
  src/components/Header/Header.css
  src/components/OngoingIncidents/OngoingIncidents.css
  src/components/OngoingIncidents/OngoingIncidents.js
  src/components/ResolvedIncidents/ResolvedIncidents.css
  src/components/ResolvedIncidents/ResolvedIncidents.js
  src/utilities.js
Labels: enhancement, frontend, phase2

#27 Update NewContactForm to function with add new contact endpoint
  src/components/NewContactForm/NewContactForm.css
  src/components/NewContactForm/NewContactForm.js
Labels: enhancement, frontend, phase2

#31 Incident form
  src/Icons/hurricane.svg
  src/components/IncidentForm/IncidentForm.js
  src/components/NewContactForm/NewContactForm.js
  src/components/ResolvedIncidents/ResolvedIncidents.css
  src/utilities.js
Labels: enhancement, frontend, phase2

#32 Incident info
  cypress/videos/quick-command-tests.js.mp4
  src/components/IncidentInfo/IncidentInfo.css
  src/components/IncidentInfo/IncidentInfo.js
  src/components/IncidentInfo/IncidentInfoSlice.js
  src/utilities.js
Labels: enhancement, feature, frontend

#33 Feature/response protocol
  cypress/fixtures/ogoing-incidents.json
  cypress/fixtures/resolved-incidents.json
  src/components/App/App.css
  src/components/DatabaseMenu/DatabaseMenu.css
  src/components/DatabaseMenu/DatabaseMenu.js
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/IncidentInfo/IncidentInfo.css
  src/components/IncidentInfo/IncidentInfo.js
  src/components/OngoingIncidents/OngoingIncidents.css
  src/components/Passport/Passport.css
  src/components/Passport/Passport.js
  src/utilities.js
Labels: enhancement, feature, frontend, phase2

#35 Feature/responsiveness
  cypress/integration/quick-command-tests.js
  public/qc-logo-9.png
  src/API-calls.js
  src/components/App/App.css
  src/components/ContactShowCard/ContactShowCard.js
  src/components/DatabaseMenu/DatabaseMenu.css
  src/components/DatabaseMenu/DatabaseMenu.js
  src/components/DatabaseSearch/DatabaseSearch.css
  src/components/DatabaseSearch/DatabaseSearch.js
  src/components/DatabaseSearch/DatabaseSearchSlice.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/IncidentForm/IncidentForm.css
  src/components/IncidentForm/IncidentForm.js
  src/components/IncidentsMenu/IncidentsMenu.css
  src/components/IncidentsMenu/IncidentsMenu.js
  src/components/NewContactForm/NewContactForm.css
  src/components/NewContactForm/NewContactForm.js
  src/components/OngoingIncidents/OngoingIncidents.css
  src/components/ResolvedIncidents/ResolvedIncidents.css
Labels: enhancement, frontend

#36 Feature/response protocol
  cypress/integration/quick-command-tests.js
  cypress/screenshots/quick-command-tests.js/QuickCommand -- dashboard view (default view INCIDENTS) -- has a header with navlinks a logo (failed).png
  cypress/videos/quick-command-tests.js.mp4
  src/Icons/checkmark.svg
  src/Icons/earthquakeMod.svg
  src/Icons/error.svg
  src/Icons/flood.svg
  src/Icons/hazard.svg
  src/components/Footer/Footer.js
  src/components/Header/Header.js
  src/components/IncidentForm/IncidentForm.css
  src/components/IncidentForm/IncidentForm.js
  src/components/IncidentInfo/IncidentInfo.css
  src/components/IncidentInfo/IncidentInfo.js
  src/components/NewContactForm/NewContactForm.js
  src/components/OngoingIncidents/OngoingIncidents.js
  src/components/ResolvedIncidents/ResolvedIncidents.css
  src/components/ResolvedIncidents/ResolvedIncidents.js
  src/utilities.js
Labels: feature, frontend

#38 Feature/new org chart
  cypress/integration/quick-command-tests.js
  package-lock.json
  package.json
  src/API-calls.js
  src/Store/store.js
  src/components/App/App.js
  src/components/ChartView/ChartView.js
  src/components/ChartView/ChartViewSlice.js
  src/components/IncidentInfo/IncidentInfo.js
  src/components/IncidentInfo/IncidentInfoSlice.js
  src/components/NewContactForm/NewContactForm.js
  src/components/OrgChart/OrgChart.js
  src/components/PositionAssignment/PositionAssignment.css
  src/components/PositionAssignment/PositionAssignment.js
  src/components/PositionAssignment/PositionAssignmentSlice.js
Labels: feature

#41 Handle error
  cypress/videos/quick-command-tests.js.mp4
  src/API-calls.js
  src/Store/Store.js
  src/Store/store.js
  src/components/App/App.js
  src/components/ChartView/ChartView.js
  src/components/IncidentInfo/IncidentInfo.css
  src/components/IncidentInfo/IncidentInfo.js
  src/components/IncidentInfo/IncidentInfoSlice.js
  src/components/OrgChart/OrgChart.js
  src/components/PositionAssignment/PositionAssignment.js
  src/components/WeatherReport/WeatherReport.css
  src/components/WeatherReport/WeatherReport.js
  src/utilities.js
Labels: enhancement, feature, frontend

#43 Test database
  cypress/integration/quick-command-tests.js
  src/components/DatabaseSearch/DatabaseSearch.js
  src/components/IncidentInfo/IncidentInfo.js
  src/components/NewContactForm/NewContactForm.js
  src/utilities.js
Labels: Phase 3, frontend

#44 Feature/form validation
  src/components/IncidentForm/IncidentForm.css
  src/components/IncidentForm/IncidentForm.js
  src/components/NewContactForm/NewContactForm.js
Labels: frontend

#46 Wave eval
  cypress/integration/quick-command-tests.js
  cypress/videos/quick-command-tests.js.mp4
  public/favicon.ico
  public/manifest.json
  public/qc-logo-6.jpeg
  public/qc-logo-7-removebg-preview.png
  public/user-story1.png
  src/Icons/error.svg
  src/components/ChartView/ChartView.css
  src/components/Footer/Footer.css
  src/components/Header/Header.css
  src/components/IncidentForm/IncidentForm.css
  src/components/IncidentForm/IncidentForm.js
  src/components/NewContactForm/NewContactForm.css
  src/components/OngoingIncidents/OngoingIncidents.css
  src/components/OngoingIncidents/OngoingIncidents.js
  src/components/OrgChart/OrgChart.css
  src/components/OrgChart/OrgChart.js
  src/components/ResolvedIncidents/ResolvedIncidents.css
  src/components/ResolvedIncidents/ResolvedIncidents.js
  src/components/WeatherReport/WeatherReport.css
  src/components/WeatherReport/WeatherReport.js
  src/utilities.js
Labels: Phase 3, frontend
